/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./grammar.macro.js#6bfadea07db496ac53b73e643cc297862e277de7
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
var _JSON$grammar;
let _initProto, _StringDecs, _NotANumberDecs, _UndefinedDecs;
import { spam as m, re } from '@bablr/boot';
import { o, eat, eatMatch, match, fail } from '@bablr/helpers/grammar';
import { CoveredBy, Node } from '@bablr/helpers/decorators';
import * as JSON from '@bablr/language-en-json';
import { buildString } from '@bablr/helpers/builders';
import { basicTriviaEnhancer } from '@bablr/helpers/trivia';
export const type = Symbol.for('@bablr/language');
export const canonicalURL = 'https://bablr.org/languages/core/en/cstml-json';
export const {
  dependencies
} = JSON;
export const getCooked = (escapeNode, span, ctx) => {
  let cooked = JSON.getCooked(escapeNode, span, ctx);
  if (cooked >= '\uD800' && cooked <= '\uDFFF') {
    throw new Error('unpaired surrogates are invalid in CSTML JSON');
  }
  return cooked;
};
export const grammar = basicTriviaEnhancer({
  triviaIsAllowed: s => s.span === 'Bare',
  triviaMatcher: m`#: <*Space:Space /[ \n\r\t]/ />`
}, class BABLRVMInstructionGrammar extends (_JSON$grammar = JSON.grammar) {
  static {
    [_initProto] = _applyDecs(this, [[_StringDecs, 2, "String"], [Node, 2, "Property"], [Node, 2, "Identifier"], [Node, 2, "IdentifierContent"], [_NotANumberDecs, 2, "NotANumber"], [_UndefinedDecs, 2, "Undefined"]], [], 0, void 0, _JSON$grammar).e;
  }
  constructor(...args) {
    super(...args);
    _initProto(this);
  }
  *[(_StringDecs = [CoveredBy('Expression'), Node], _NotANumberDecs = [CoveredBy('Expression'), Node], _UndefinedDecs = [CoveredBy('Expression'), Node], "Expression")](props) {
    if (yield match('NaN')) {
      yield eat(m`<NotANumber />`);
    } else if (yield match('undefined')) {
      yield eat(m`<Undefined />`);
    } else {
      yield* super.Expression(props);
    }
  }
  *String({
    ctx
  }) {
    let q = yield match(re`/['"]/`);
    if (!q) yield fail();
    const q_ = ctx.sourceTextFor(q);
    yield q_ === "'" ? eat(m`openToken: <*Punctuator "'" { balanced: "'", balancedSpan: 'String:Single' } />`) : eat(m`openToken: <*Punctuator '"' { balanced: '"', balancedSpan: 'String:Double' } />`);
    yield eat(m`content$: <*StringContent />`);
    yield q_ === "'" ? eat(m`closeToken: <*Punctuator "'" { balancer: true } />`) : eat(m`closeToken: <*Punctuator '"' { balancer: true } />`);
  }
  *Property() {
    if (yield match(re`/['"]/`)) {
      yield eatMatch(m`key$: <String />`);
    } else {
      yield eatMatch(m`key$: <Identifier />`);
    }
    yield eat(m`sigilToken: <*Punctuator ':' />`);
    yield eat(m`value+$: <__Expression />`);
  }
  *Identifier({
    ctx
  }) {
    let q;
    let pn = ctx.sourceTextFor(yield match(re`/["']/`));
    if (pn) {
      q = yield eatMatch(m`openToken: <*Punctuator ${buildString(pn)} { balanced: ${buildString(pn)} } />`, o({}), o({
        bind: true
      }));
    } else {
      q = yield eat(m`openToken: null`);
    }
    yield eat(m`content: <*IdentifierContent { span: 'Identifier' } />`, o({
      quoted: !!q
    }));
    if (q) {
      yield eat(m`closeToken: <*Punctuator ${buildString(pn)} { balancer: true } />`, o({}), o({
        bind: true
      }));
    } else {
      yield eat(m`closeToken: null`);
    }
  }
  *IdentifierContent({
    props: {
      quoted = false
    }
  }) {
    let lit, esc;
    do {
      if (esc = yield match('\\')) {
        esc = yield eatMatch(m`@: <EscapeSequence />`);
      } else {
        if (!quoted) {
          lit = yield eatMatch(re`/[a-zA-Z\u{80}-\u{10ffff}][a-zA-Z0-9_\u{80}-\u{10ffff}-]*/`);
        } else {
          lit = yield eatMatch(re`/[^\u0060\r\n]+/`);
        }
      }
    } while (lit || esc);
  }
  *NotANumber() {
    yield eat(m`sigilToken: <*Keyword 'NaN' />`);
  }
  *Undefined() {
    yield eat(m`sigilToken: <*Keyword 'undefined' />`);
  }
});