/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./grammar.macro.js#75919786f0d17d91283f52191c167782f029a720
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
var _JSON$grammar;
let _initProto, _NotANumberDecs, _UndefinedDecs;
import { spam as m } from '@bablr/boot';
import { eat, match } from '@bablr/helpers/grammar';
import { CoveredBy, Node } from '@bablr/helpers/decorators';
import * as JSON from '@bablr/language-en-json';
export const type = Symbol.for('@bablr/language');
export const canonicalURL = 'https://bablr.org/languages/core/en/cstml-json';
export const {
  dependencies
} = JSON;
export const getCooked = (escapeNode, span, ctx) => {
  let cooked = JSON.getCooked(escapeNode, span, ctx);
  if (cooked >= '\uD800' && cooked <= '\uDFFF') {
    throw new Error('unpaired surrogates are invalid in CSTML JSON');
  }
  return cooked;
};
export const grammar = class BABLRVMInstructionGrammar extends (_JSON$grammar = JSON.grammar) {
  static {
    [_initProto] = _applyDecs(this, [[_NotANumberDecs, 2, "NotANumber"], [_UndefinedDecs, 2, "Undefined"]], [], 0, void 0, _JSON$grammar).e;
  }
  constructor(...args) {
    super(...args);
    _initProto(this);
  }
  *[(_NotANumberDecs = [CoveredBy('Expression'), Node], _UndefinedDecs = [CoveredBy('Expression'), Node], "Expression")](props) {
    if (yield match('NaN')) {
      yield eat(m`<NotANumber />`);
    } else if (yield match('undefined')) {
      yield eat(m`<Undefined />`);
    } else {
      yield* super.Expression(props);
    }
  }
  *NotANumber() {
    yield eat(m`sigilToken: <*Keyword 'NaN' />`);
  }
  *Undefined() {
    yield eat(m`sigilToken: <*Keyword 'undefined' />`);
  }
};