/* @macrome
 * @generatedby @bablr/macrome-generator-bablr
 * @generatedfrom ./grammar.macro.js#0a642a38394d3786460fc65bbdb11a747007cd42
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import _applyDecs from "@babel/runtime/helpers/applyDecs2305";
var _JSON$grammar;
let _initProto, _NaNDecs;
import { re, spam as m } from '@bablr/boot';
import { extendLanguage, o, eat, match } from '@bablr/helpers/grammar';
import { CoveredBy, Node, InjectFrom } from '@bablr/helpers/decorators';
import * as JSON from '@bablr/language-en-json';
import * as productions from '@bablr/helpers/productions';
import { buildString } from '@bablr/helpers/builders';
export const canonicalURL = 'https://bablr.org/languages/core/en/cstml-json';
export const {
  dependencies
} = JSON;
export const getCooked = (escapeNode, span, ctx) => {
  let cooked = JSON.getCooked(escapeNode, span, ctx);
  if (cooked >= '\uD800' && cooked <= '\uDFFF') {
    throw new Error('unpaired surrogates are invalid in CSTML JSON');
  }
  return cooked;
};
export const grammar = class BABLRVMInstructionGrammar extends (_JSON$grammar = JSON.grammar) {
  static {
    [_initProto] = _applyDecs(this, [[_NaNDecs, 2, "NaN"]], [], 0, void 0, _JSON$grammar).e;
  }
  constructor(...args) {
    super(...args);
    _initProto(this);
  }
  *[(_NaNDecs = [CoveredBy('Expression'), Node], "Expression")](props) {
    if (yield match('NaN')) {
      yield eat(m`<NaN />`);
    } else {
      yield* super.Expression(props);
    }
  }
  *NaN() {
    yield eat(m`sigilToken: <*Keyword 'NaN' />`);
  }
};